[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:postgresql]
command=/usr/local/sbin/proxbox-stack-postgresql
priority=10
autorestart=true
startsecs=5
stopsignal=INT
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1 ::1 --protected-mode yes --dir /var/lib/redis --save 60 1
user=redis
priority=20
autorestart=true
startsecs=2
stopsignal=TERM
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:proxbox-api]
command=/usr/local/sbin/proxbox-stack-backend
user=netbox
environment=HOME="/var/lib/proxbox-api"
priority=30
autorestart=true
startsecs=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:netbox]
command=/usr/local/sbin/proxbox-stack-netbox
user=netbox
environment=HOME="/opt/netbox"
priority=40
autorestart=true
startsecs=10
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:netbox-rqworker]
command=/usr/local/sbin/proxbox-stack-rqworker
user=netbox
environment=HOME="/opt/netbox"
priority=50
autorestart=true
startsecs=10
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
