# Generated by Django 5.2.12 on 2026-03-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0010_squashed_plugin_settings_and_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmbackup',
            name='storage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
