# Generated by Django 5.2.12 on 2026-03-30 13:19

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_proxbox', '0013_make_domains_optional_and_require_host_target'),
        ('virtualization', '0052_gfk_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('vmid', models.IntegerField()),
                ('node', models.CharField(max_length=255)),
                ('snaptime', models.DateTimeField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('subtype', models.CharField(default='qemu', max_length=255)),
                ('status', models.CharField(default='active', max_length=255)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'VM Snapshot',
                'verbose_name_plural': 'VM Snapshots',
                'ordering': ('virtual_machine', 'node', 'name'),
                'unique_together': {('vmid', 'name', 'node')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
