# Generated by Django 5.2.12 on 2026-03-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0013_proxmoxstorage_cluster_foreignkey'),
        ('virtualization', '0052_gfk_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxmoxstorage',
            options={'ordering': ('cluster__name', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='proxmoxstorage',
            unique_together={('cluster', 'name')},
        ),
    ]
