# Generated by Django — drop legacy SyncProcess (syncs are NetBox Jobs only).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_proxbox", "0014_vmsnapshot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SyncProcess",
        ),
    ]
