"""Django migration for netbox_proxbox."""

# Generated by Django 5.2.12 on 2026-04-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_proxbox", "0018_proxmoxcluster_tags_proxmoxnode_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRoutine",
            fields=[
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom field data stored as JSON.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        help_text="ProxmoxEndpoint this backup routine is discovered from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_routines",
                        to="netbox_proxbox.proxmoxendpoint",
                        verbose_name="Proxmox endpoint",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        help_text="Unique Proxmox job identifier (e.g. 'local:123').",
                        max_length=255,
                        verbose_name="Job ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this backup job is currently enabled.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Systemd calendar format schedule string (e.g. 'daily 04:00').",
                        max_length=255,
                        verbose_name="Schedule",
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="Computed next scheduled run time.",
                        null=True,
                        verbose_name="Next Run",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Node to run backup on (null = all nodes).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_routines",
                        to="netbox_proxbox.proxmoxnode",
                        verbose_name="Node",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target storage for backup files.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_routines",
                        to="netbox_proxbox.proxmoxstorage",
                        verbose_name="Storage",
                    ),
                ),
                (
                    "selection",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of VMID values selected for this backup job.",
                        verbose_name="Selection",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description or notes for this backup routine.",
                        verbose_name="Comment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("stale", "Stale")],
                        default="active",
                        help_text="Active or stale — stale routines no longer exist in Proxmox.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "keep_last",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of last backups to retain.",
                        null=True,
                        verbose_name="Keep Last",
                    ),
                ),
                (
                    "keep_daily",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of daily backups to retain.",
                        null=True,
                        verbose_name="Keep Daily",
                    ),
                ),
                (
                    "keep_weekly",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of weekly backups to retain.",
                        null=True,
                        verbose_name="Keep Weekly",
                    ),
                ),
                (
                    "keep_monthly",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of monthly backups to retain.",
                        null=True,
                        verbose_name="Keep Monthly",
                    ),
                ),
                (
                    "keep_yearly",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of yearly backups to retain.",
                        null=True,
                        verbose_name="Keep Yearly",
                    ),
                ),
                (
                    "keep_all",
                    models.BooleanField(
                        blank=True,
                        help_text="Retain all backups regardless of other retention settings.",
                        null=True,
                        verbose_name="Keep All",
                    ),
                ),
                (
                    "notes_template",
                    models.TextField(
                        blank=True,
                        help_text="Template string for generating backup notes. Supports {{cluster}}, {{guestname}}, {{node}}, {{vmid}}.",
                        verbose_name="Notes Template",
                    ),
                ),
                (
                    "bwlimit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="I/O bandwidth limit in KiB/s (0 = unlimited).",
                        null=True,
                        verbose_name="Bandwidth Limit",
                    ),
                ),
                (
                    "zstd",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of zstd compression threads (0 = auto).",
                        null=True,
                        verbose_name="Zstd Threads",
                    ),
                ),
                (
                    "io_workers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of IO workers for parallel processing.",
                        null=True,
                        verbose_name="IO Workers",
                    ),
                ),
                (
                    "fleecing",
                    models.CharField(
                        blank=True,
                        help_text="Options for backup fleecing (VM only).",
                        max_length=255,
                        verbose_name="Fleecing",
                    ),
                ),
                (
                    "fleecing_storage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Storage to use for fleecing operations.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="netbox_proxbox.proxmoxstorage",
                        verbose_name="Fleecing Storage",
                    ),
                ),
                (
                    "repeat_missed",
                    models.BooleanField(
                        blank=True,
                        help_text="Run the job as soon as possible if it was missed while the scheduler was not running.",
                        null=True,
                        verbose_name="Repeat Missed",
                    ),
                ),
                (
                    "pbs_change_detection_mode",
                    models.CharField(
                        blank=True,
                        help_text="PBS mode used to detect file changes for container backups.",
                        max_length=50,
                        verbose_name="PBS Change Detection Mode",
                    ),
                ),
                (
                    "raw_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full raw configuration from Proxmox API for reference.",
                        verbose_name="Raw Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Routine",
                "verbose_name_plural": "Backup Routines",
                "ordering": ("endpoint", "job_id"),
            },
        ),
        migrations.AddConstraint(
            model_name="backuproutine",
            constraint=models.UniqueConstraint(
                fields=("endpoint", "job_id"),
                name="netbox_proxbox_backuproutine_unique_endpoint_job_id",
            ),
        ),
    ]
