# Generated by Django 5.2.12 on 2026-04-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_proxbox", "0019_backup_routine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Replication",
            fields=[
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom field data stored as JSON.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "replication_id",
                    models.CharField(
                        help_text="Replication job ID. Composed of guest ID and job number: '<GUEST>-<JOBNUM>'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "guest",
                    models.PositiveIntegerField(help_text="Guest ID (VM ID)."),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="Target node for replication.",
                        max_length=255,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("local", "Local")],
                        default="local",
                        help_text="Replication type.",
                        max_length=50,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Replication schedule (systemd calendar format).",
                        max_length=128,
                    ),
                ),
                (
                    "rate",
                    models.FloatField(
                        blank=True,
                        help_text="Rate limit in MB/s.",
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Description of the replication job.",
                        null=True,
                    ),
                ),
                (
                    "disable",
                    models.BooleanField(
                        default=False,
                        help_text="Flag to disable the entry.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source node (for internal use, to detect if the guest was stolen).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jobnum",
                    models.PositiveIntegerField(
                        help_text="Unique, sequential ID assigned to each job."
                    ),
                ),
                (
                    "remove_job",
                    models.CharField(
                        blank=True,
                        choices=[("local", "Local"), ("full", "Full")],
                        help_text="Mark the replication job for removal.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "proxmox_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target Proxmox node for replication.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replications",
                        to="netbox_proxbox.proxmoxnode",
                    ),
                ),
                (
                    "virtual_machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replications",
                        to="virtualization.virtualmachine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replication",
                "verbose_name_plural": "Replications",
                "ordering": ("virtual_machine", "replication_id"),
            },
        ),
    ]
