# Generated by Django 5.2.12 on 2026-04-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_proxbox', '0025_add_operational_settings'),
        ('virtualization', '0052_gfk_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proxmoxstorage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proxmoxstoragevirtualdisk',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vmbackup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vmsnapshot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='proxmoxstorage',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='unique_proxmox_storage_cluster_name'),
        ),
        migrations.AddConstraint(
            model_name='proxmoxstoragevirtualdisk',
            constraint=models.UniqueConstraint(fields=('proxmox_storage', 'virtual_disk'), name='unique_proxmox_storage_virtual_disk'),
        ),
        migrations.AddConstraint(
            model_name='vmbackup',
            constraint=models.UniqueConstraint(fields=('storage', 'virtual_machine', 'subtype', 'format', 'volume_id', 'vmid'), name='unique_vm_backup_fields'),
        ),
        migrations.AddConstraint(
            model_name='vmsnapshot',
            constraint=models.UniqueConstraint(fields=('vmid', 'name', 'node'), name='unique_vm_snapshot_vmid_name_node'),
        ),
    ]
