# Generated by Django 6.0.4 on 2026-04-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0031_proxmoxendpoint_site_tenant'),
        ('netbox_proxbox', '0031_proxmoxendpoint_timeout_retries_pluginsettings_proxmox_defaults'),
    ]

    operations = [
    ]
