# Generated by Django 6.0.5 on 2026-06-02 21:55

import django.core.validators
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0048_interface_batch_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxboxpluginsettings',
            name='interface_batch_size',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='proxmoxvmtemplate',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
