# Generated by Django 6.0.5 on 2026-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0049_alter_proxboxpluginsettings_interface_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxboxpluginsettings',
            name='enable_tenant_tag_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxmoxendpoint',
            name='enable_tenant_tag_assignment',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
