# Generated by Django 6.0.5 on 2026-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0050_proxboxpluginsettings_enable_tenant_tag_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxboxpluginsettings',
            name='sync_mode_vm_interface',
            field=models.CharField(
                choices=[
                    ('always', 'Always'),
                    ('bootstrap_only', 'Bootstrap only'),
                    ('disabled', 'Disabled'),
                ],
                default='always',
                help_text='Controls synchronization of VM interfaces discovered from Proxmox.',
                max_length=16,
                verbose_name='VM interface sync mode',
            ),
        ),
        migrations.AddField(
            model_name='proxboxpluginsettings',
            name='sync_mode_mac',
            field=models.CharField(
                choices=[
                    ('always', 'Always'),
                    ('bootstrap_only', 'Bootstrap only'),
                    ('disabled', 'Disabled'),
                ],
                default='always',
                help_text='Controls MAC address reconciliation for VM interfaces.',
                max_length=16,
                verbose_name='MAC address sync mode',
            ),
        ),
        migrations.AddField(
            model_name='proxmoxendpoint',
            name='sync_mode_vm_interface',
            field=models.CharField(
                blank=True,
                choices=[
                    ('always', 'Always'),
                    ('bootstrap_only', 'Bootstrap only'),
                    ('disabled', 'Disabled'),
                ],
                help_text='Per-endpoint override for VM interface sync. Leave blank to inherit.',
                max_length=16,
                null=True,
                verbose_name='VM interface sync mode',
            ),
        ),
        migrations.AddField(
            model_name='proxmoxendpoint',
            name='sync_mode_mac',
            field=models.CharField(
                blank=True,
                choices=[
                    ('always', 'Always'),
                    ('bootstrap_only', 'Bootstrap only'),
                    ('disabled', 'Disabled'),
                ],
                help_text='Per-endpoint override for VM interface MAC sync. Leave blank to inherit.',
                max_length=16,
                null=True,
                verbose_name='MAC address sync mode',
            ),
        ),
    ]
